### ISSUE TITLE
TS error caused by "hybrid" output mode not available anymore on Astro 5

### ISSUE THREAD

**Issue by ref-thomasledoux1** [shishkin/astro-pagefind#90] opened 2024-09-22 11:39 UTC
When upgrading to Astro v5 (beta), I noticed that my build started failing on node_modules/astro-pagefind/src/pagefind.ts.
The error is caused by a check for `config.output` where it's compared to `hybrid`.
Since this output mode doesn't exist anymore in v5 of Astro, the check fails.
Not sure how you could fix it without breaking it for v4 (and before) users though..

<img width="1032" alt="Screenshot 2024-09-22 at 13 35 53" src="https://github.com/user-attachments/assets/653caa77-2f03-4155-87af-997061523930">

**Comment by shishkin** [comment] 2024-09-23 10:24
Thanks for the heads-up. We can always cast it to string before comparing. I need to check again if I can simplify this code in newer Astro versions. Basically, `config.outDir` supposed to be enough but I had issues with it in hybrid before.

**Comment by dallyh** [comment] 2024-11-24 22:56
I've now encountered another issue which comes with Astro 5 and this integration. I'm using node adapter and the files are built into `dist` whereas astro with node builds client assets into `dist/client`. It is probably caused by the condition of `output === hybrid` which is not met.

I guess for now simply a config option to manually set the outdir could work.

**Comment by shishkin** [comment] 2024-12-07 18:27
Fixed in [v1.7.0](https://github.com/shishkin/astro-pagefind/releases/tag/v1.7.0)

**Closed by shishkin** 2024-12-07 18:27 UTC
