### ISSUE TITLE
I have set it up, why can't I search for my content?

### ISSUE THREAD

**Issue by sunheyi6** [shishkin/astro-pagefind#89] opened 2024-09-10 03:34 UTC
I have started the local dev, but the search found that I could not find the local content
![image](https://github.com/user-attachments/assets/248ce3fe-179f-49c7-995e-d60600135ec2)

**Comment by shishkin** [comment] 2024-09-10 09:14
Sorry, it's difficult to tell what went wrong without a reproduction example. Maybe you forgot to run build once to initially create pagefind index?

**Comment by sunheyi6** [comment] 2024-09-12 02:48
> Sorry, it's difficult to tell what went wrong without a reproduction example. Maybe you forgot to run build once to initially create pagefind index?

I have found the issue. The search function works on the server but not locally. I tried it out. This function searches for all content in the articles. How can I modify it to only search for titles?

**Comment by shishkin** [comment] 2024-09-12 07:23
You still need to know about [pagefind](https://pagefind.app) and read its documentation in order to use this integration. I'll close this for now since the issue is resolved.

**Closed by shishkin** 2024-09-12 07:23 UTC
